### ISSUE TITLE
env vars not found by extension?

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/vault-lambda-extension#89]
Sorry for being an idiot - but I'm unable to get the extension (layer version 14?) to see the env vars, despite having included one of each and both at the same time `VAULT_ADDR` and `VLE_VAULT_ADDR` and confirmed in the AWS UI that the env vars are set.

When I try to execute a function with the extension, the missing env var error shows up

```
[INFO]  vault-lambda-extension: Initialising
[ERROR] Fatal error, exiting: error="missing VLE_VAULT_ADDR, VAULT_ADDR, VAULT_AUTH_PROVIDER or VAULT_AUTH_ROLE environment variables"
```

The error seems to be coming from [this check](https://github.com/hashicorp/vault-lambda-extension/blob/6ea4397aba586395827b06e96e0a230562097e5d/main.go#L106-L108), but AFAICT, [auth.go](https://github.com/hashicorp/vault-lambda-extension/blob/7db7a31277a4f5ae99e1e1fcbe144fd5342cd114/internal/config/auth.go) never even looks for an env var `VAULT_ADDR` - only `VLE_VAULT_ADDR`. Either way, I can't seem to get the extension to see either env var. Any suggestions would be appreciated.

## Moar details

To keep it simple for now, I'm using aws SAM, with a globals declaration showing the env vars in template.yaml:

```
Globals:
  Function:
    ...
    Environment:
      Variables:
        VAULT_ADDR: http://127.0.0.1:8200
        VLE_VAULT_ADDR: http://127.0.0.1:8200
```

The resources block is also as simple:

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - arn:aws:lambda:us-west-2:634166935893:layer:vault-lambda-extension:14
```

The (python) function code itself (which I don't believe is in play here) uses the hvac module but is again, simple:

```
    vault = hvac.Client(url=os.environ['VAULT_ADDR'])
    read_response = vault.secrets.kv.read_secret_version(path='secret/chef/cookie')
    val = read_response['data']['data']['best']
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": f"best cookie: {val}",
        }),
    }
```
